name: Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  chat:
    name: Checks
    timeout-minutes: 15
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          fetch-depth: '0'
      - uses: actions/setup-python@v4.4.0
        with:
          python-version: 3.11
          cache: 'pip'
      - name: Bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle check || bundle install --jobs 4 --retry 3
      - name: Install driver
        run: |
          brew install facebook/fb/idb-companion
          pip install -r requirements.txt
      - name: Rake
        run: bundle exec rake
